apiVersion: v1
kind: Pod
metadata:
  name: check-db
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  containers:
  - name: check-db
    image: postgres:12
    command: ['psql']
    args: ['-c', 'SELECT current_database();']
    env:
    - name: PGDATABASE
      value: postgres
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: fox-psqldb
          key: endpoint
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: fox-psqldb
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: fox-psqldb
          key: password
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: fox-psqldb
          key: port
