---
apiVersion: database.azure.crossplane.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: fox-psqldb
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  forProvider:
    administratorLogin: foxadmin
    resourceGroupNameRef:
      name: rg-crossplane
    location: eastus
    minimalTlsVersion: TLS1_2
    sslEnforcement: Disabled
    version: "11"
    sku:
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretToRef:
    namespace: crossplane
    name: fox-psqldb
  providerConfigRef:
    name: default
