apiVersion: database.azure.crossplane.io/v1alpha3
kind: PostgreSQLInstance
metadata:
  name: my-db
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: azure
  writeConnectionSecretToRef:
    name: db-conn
