apiVersion: network.azure.crossplane.io/v1alpha3
kind: VirtualNetwork
metadata:
  name: vn-crossplane
spec:
  resourceGroupNameRef:
    name: rg-crossplane
  location: eastus
  properties:
    addressSpace:
      addressPrefixes:
        - 10.2.0.0/16
  providerConfigRef:
    name: default
