apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crosplane-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
